// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_sessions.sql

package sqlc

import (
	"context"
	"time"
)

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id,subject_id,subject_security_version,session_access,csrf_token_hash,expires_at
FROM identity_sessions
WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND idle_expires_at>?
`

type GetActiveSessionByTokenHashParams struct {
	TokenHash     []byte    `json:"token_hash"`
	ExpiresAt     time.Time `json:"expires_at"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
}

type GetActiveSessionByTokenHashRow struct {
	ID                     string    `json:"id"`
	SubjectID              string    `json:"subject_id"`
	SubjectSecurityVersion int64     `json:"subject_security_version"`
	SessionAccess          string    `json:"session_access"`
	CsrfTokenHash          []byte    `json:"csrf_token_hash"`
	ExpiresAt              time.Time `json:"expires_at"`
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, arg GetActiveSessionByTokenHashParams) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByTokenHash, arg.TokenHash, arg.ExpiresAt, arg.IdleExpiresAt)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.SubjectSecurityVersion,
		&i.SessionAccess,
		&i.CsrfTokenHash,
		&i.ExpiresAt,
	)
	return i, err
}
