// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO identity_audit_events(
    id, event_action, outcome, actor_subject_id, target_subject_id,
    request_id, source_hash, metadata, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ID              string         `json:"id"`
	EventAction     string         `json:"event_action"`
	Outcome         string         `json:"outcome"`
	ActorSubjectID  sql.NullString `json:"actor_subject_id"`
	TargetSubjectID sql.NullString `json:"target_subject_id"`
	RequestID       sql.NullString `json:"request_id"`
	SourceHash      []byte         `json:"source_hash"`
	Metadata        string         `json:"metadata"`
	CreatedAt       time.Time      `json:"created_at"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.EventAction,
		arg.Outcome,
		arg.ActorSubjectID,
		arg.TargetSubjectID,
		arg.RequestID,
		arg.SourceHash,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
