// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"
	"time"
)

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO identity_password_credentials(
    id, subject_id, password_hash, password_revision, credential_status,
    changed_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePasswordCredentialParams struct {
	ID               string    `json:"id"`
	SubjectID        string    `json:"subject_id"`
	PasswordHash     string    `json:"password_hash"`
	PasswordRevision int64     `json:"password_revision"`
	CredentialStatus string    `json:"credential_status"`
	ChangedAt        time.Time `json:"changed_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordCredential,
		arg.ID,
		arg.SubjectID,
		arg.PasswordHash,
		arg.PasswordRevision,
		arg.CredentialStatus,
		arg.ChangedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
