// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identifiers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createIdentifier = `-- name: CreateIdentifier :exec
INSERT INTO identity_identifiers(
    id, subject_id, identifier_type, identifier_value, normalized_value,
    identifier_usage, status, verified_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateIdentifierParams struct {
	ID              string       `json:"id"`
	SubjectID       string       `json:"subject_id"`
	IdentifierType  string       `json:"identifier_type"`
	IdentifierValue string       `json:"identifier_value"`
	NormalizedValue string       `json:"normalized_value"`
	IdentifierUsage string       `json:"identifier_usage"`
	Status          string       `json:"status"`
	VerifiedAt      sql.NullTime `json:"verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) CreateIdentifier(ctx context.Context, arg CreateIdentifierParams) error {
	_, err := q.db.ExecContext(ctx, createIdentifier,
		arg.ID,
		arg.SubjectID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.NormalizedValue,
		arg.IdentifierUsage,
		arg.Status,
		arg.VerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
