// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_credentials.sql

package sqlc

import (
	"context"
)

const getLoginCredentialByNormalizedIdentifier = `-- name: GetLoginCredentialByNormalizedIdentifier :one
SELECT i.subject_id,c.password_hash,c.credential_status
FROM identity_identifiers i JOIN identity_password_credentials c ON c.subject_id=i.subject_id
WHERE i.normalized_value=? AND i.status=? AND i.identifier_usage IN(?,?)
LIMIT 1
`

type GetLoginCredentialByNormalizedIdentifierParams struct {
	NormalizedValue   string `json:"normalized_value"`
	Status            string `json:"status"`
	IdentifierUsage   string `json:"identifier_usage"`
	IdentifierUsage_2 string `json:"identifier_usage_2"`
}

type GetLoginCredentialByNormalizedIdentifierRow struct {
	SubjectID        string `json:"subject_id"`
	PasswordHash     string `json:"password_hash"`
	CredentialStatus string `json:"credential_status"`
}

func (q *Queries) GetLoginCredentialByNormalizedIdentifier(ctx context.Context, arg GetLoginCredentialByNormalizedIdentifierParams) (GetLoginCredentialByNormalizedIdentifierRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginCredentialByNormalizedIdentifier,
		arg.NormalizedValue,
		arg.Status,
		arg.IdentifierUsage,
		arg.IdentifierUsage_2,
	)
	var i GetLoginCredentialByNormalizedIdentifierRow
	err := row.Scan(&i.SubjectID, &i.PasswordHash, &i.CredentialStatus)
	return i, err
}
