// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type IdentityAuditEvent struct {
	ID              string         `json:"id"`
	EventAction     string         `json:"event_action"`
	Outcome         string         `json:"outcome"`
	ActorSubjectID  sql.NullString `json:"actor_subject_id"`
	TargetSubjectID sql.NullString `json:"target_subject_id"`
	RequestID       sql.NullString `json:"request_id"`
	SourceHash      []byte         `json:"source_hash"`
	Metadata        string         `json:"metadata"`
	CreatedAt       time.Time      `json:"created_at"`
}

type IdentityIdentifier struct {
	ID              string       `json:"id"`
	SubjectID       string       `json:"subject_id"`
	IdentifierType  string       `json:"identifier_type"`
	IdentifierValue string       `json:"identifier_value"`
	NormalizedValue string       `json:"normalized_value"`
	IdentifierUsage string       `json:"identifier_usage"`
	Status          string       `json:"status"`
	VerifiedAt      sql.NullTime `json:"verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type IdentityLoginThrottle struct {
	ID              string       `json:"id"`
	IdentifierHash  []byte       `json:"identifier_hash"`
	SourceHash      []byte       `json:"source_hash"`
	FailedCount     int64        `json:"failed_count"`
	WindowStartedAt time.Time    `json:"window_started_at"`
	LockedUntil     sql.NullTime `json:"locked_until"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type IdentityPasswordCredential struct {
	ID               string    `json:"id"`
	SubjectID        string    `json:"subject_id"`
	PasswordHash     string    `json:"password_hash"`
	PasswordRevision int64     `json:"password_revision"`
	CredentialStatus string    `json:"credential_status"`
	ChangedAt        time.Time `json:"changed_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type IdentityProfile struct {
	SubjectID   string    `json:"subject_id"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type IdentityRole struct {
	ID          string    `json:"id"`
	RoleCode    string    `json:"role_code"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type IdentitySession struct {
	ID                     string         `json:"id"`
	SubjectID              string         `json:"subject_id"`
	SubjectSecurityVersion int64          `json:"subject_security_version"`
	TokenHash              []byte         `json:"token_hash"`
	CsrfTokenHash          []byte         `json:"csrf_token_hash"`
	SessionAccess          string         `json:"session_access"`
	AuthenticatedAt        time.Time      `json:"authenticated_at"`
	LastSeenAt             time.Time      `json:"last_seen_at"`
	ExpiresAt              time.Time      `json:"expires_at"`
	IdleExpiresAt          time.Time      `json:"idle_expires_at"`
	RevokedAt              sql.NullTime   `json:"revoked_at"`
	RevokedReason          sql.NullString `json:"revoked_reason"`
	Metadata               string         `json:"metadata"`
	CreatedAt              time.Time      `json:"created_at"`
}

type IdentitySubject struct {
	ID              string       `json:"id"`
	Status          string       `json:"status"`
	SecurityVersion int64        `json:"security_version"`
	DisabledAt      sql.NullTime `json:"disabled_at"`
	Metadata        string       `json:"metadata"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type IdentitySubjectRole struct {
	ID                 string         `json:"id"`
	SubjectID          string         `json:"subject_id"`
	RoleID             string         `json:"role_id"`
	GrantedBySubjectID sql.NullString `json:"granted_by_subject_id"`
	CreatedAt          time.Time      `json:"created_at"`
}
