// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"
	"time"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO identity_profiles(subject_id, display_name, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type CreateProfileParams struct {
	SubjectID   string    `json:"subject_id"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.SubjectID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
