// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AssignSubjectRole(ctx context.Context, arg AssignSubjectRoleParams) error
	CountSubjectRoleAssignments(ctx context.Context, arg CountSubjectRoleAssignmentsParams) (int64, error)
	CountSubjects(ctx context.Context) (int64, error)
	CreateIdentifier(ctx context.Context, arg CreateIdentifierParams) error
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error
	CreateProfile(ctx context.Context, arg CreateProfileParams) error
	CreateRoleIfAbsent(ctx context.Context, arg CreateRoleIfAbsentParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSubject(ctx context.Context, arg CreateSubjectParams) error
	GetActiveSessionByTokenHash(ctx context.Context, arg GetActiveSessionByTokenHashParams) (GetActiveSessionByTokenHashRow, error)
	GetActiveSessionSubjectByTokenHash(ctx context.Context, tokenHash []byte) (string, error)
	GetEnabledSubjectSecurityVersion(ctx context.Context, arg GetEnabledSubjectSecurityVersionParams) (int64, error)
	GetLoginCredentialByNormalizedIdentifier(ctx context.Context, arg GetLoginCredentialByNormalizedIdentifierParams) (GetLoginCredentialByNormalizedIdentifierRow, error)
	GetRoleIDByCode(ctx context.Context, roleCode string) (string, error)
	GetSubjectByID(ctx context.Context, id string) (IdentitySubject, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	RevokeActiveSessionByTokenHash(ctx context.Context, arg RevokeActiveSessionByTokenHashParams) (int64, error)
	TouchActiveSession(ctx context.Context, arg TouchActiveSessionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
