// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_management.sql

package sqlc

import (
	"context"
)

const countEnabledSubjectsByRoleCodeExcludingSubjectID = `-- name: CountEnabledSubjectsByRoleCodeExcludingSubjectID :one
SELECT COUNT(*)
FROM identity_subjects AS subject
JOIN identity_subject_roles AS subject_role ON subject_role.subject_id=subject.id
JOIN identity_roles AS role ON role.id=subject_role.role_id
WHERE subject.status=? AND role.role_code=? AND subject.id<>?
`

type CountEnabledSubjectsByRoleCodeExcludingSubjectIDParams struct {
	Status   string `json:"status"`
	RoleCode string `json:"role_code"`
	ID       string `json:"id"`
}

func (q *Queries) CountEnabledSubjectsByRoleCodeExcludingSubjectID(ctx context.Context, arg CountEnabledSubjectsByRoleCodeExcludingSubjectIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledSubjectsByRoleCodeExcludingSubjectID, arg.Status, arg.RoleCode, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRoleCodesBySubjectID = `-- name: ListRoleCodesBySubjectID :many
SELECT role.role_code
FROM identity_subject_roles AS subject_role
JOIN identity_roles AS role ON role.id=subject_role.role_id
WHERE subject_role.subject_id=?
ORDER BY role.role_code
`

func (q *Queries) ListRoleCodesBySubjectID(ctx context.Context, subjectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoleCodesBySubjectID, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_code string
		if err := rows.Scan(&role_code); err != nil {
			return nil, err
		}
		items = append(items, role_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
