// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const assignSubjectRole = `-- name: AssignSubjectRole :exec
INSERT INTO identity_subject_roles(id, subject_id, role_id, granted_by_subject_id, created_at)
VALUES (?, ?, ?, ?, ?)
`

type AssignSubjectRoleParams struct {
	ID                 string         `json:"id"`
	SubjectID          string         `json:"subject_id"`
	RoleID             string         `json:"role_id"`
	GrantedBySubjectID sql.NullString `json:"granted_by_subject_id"`
	CreatedAt          time.Time      `json:"created_at"`
}

func (q *Queries) AssignSubjectRole(ctx context.Context, arg AssignSubjectRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignSubjectRole,
		arg.ID,
		arg.SubjectID,
		arg.RoleID,
		arg.GrantedBySubjectID,
		arg.CreatedAt,
	)
	return err
}

const createRoleIfAbsent = `-- name: CreateRoleIfAbsent :exec
INSERT INTO identity_roles(id, role_code, display_name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(role_code) DO NOTHING
`

type CreateRoleIfAbsentParams struct {
	ID          string    `json:"id"`
	RoleCode    string    `json:"role_code"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateRoleIfAbsent(ctx context.Context, arg CreateRoleIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, createRoleIfAbsent,
		arg.ID,
		arg.RoleCode,
		arg.DisplayName,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getRoleIDByCode = `-- name: GetRoleIDByCode :one
SELECT id
FROM identity_roles
WHERE role_code = ?
`

func (q *Queries) GetRoleIDByCode(ctx context.Context, roleCode string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRoleIDByCode, roleCode)
	var id string
	err := row.Scan(&id)
	return id, err
}
