// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_assignments.sql

package sqlc

import (
	"context"
)

const countSubjectRoleAssignments = `-- name: CountSubjectRoleAssignments :one
SELECT COUNT(*)
FROM identity_subject_roles AS subject_role
JOIN identity_roles AS role ON role.id = subject_role.role_id
WHERE subject_role.subject_id = ?
  AND role.role_code = ?
`

type CountSubjectRoleAssignmentsParams struct {
	SubjectID string `json:"subject_id"`
	RoleCode  string `json:"role_code"`
}

func (q *Queries) CountSubjectRoleAssignments(ctx context.Context, arg CountSubjectRoleAssignmentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubjectRoleAssignments, arg.SubjectID, arg.RoleCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}
