// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_versions.sql

package sqlc

import (
	"context"
)

const getEnabledSubjectSecurityVersion = `-- name: GetEnabledSubjectSecurityVersion :one
SELECT security_version
FROM identity_subjects
WHERE id=? AND status=?
`

type GetEnabledSubjectSecurityVersionParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) GetEnabledSubjectSecurityVersion(ctx context.Context, arg GetEnabledSubjectSecurityVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEnabledSubjectSecurityVersion, arg.ID, arg.Status)
	var security_version int64
	err := row.Scan(&security_version)
	return security_version, err
}
