// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_revocation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const revokeActiveSessionsBySubjectID = `-- name: RevokeActiveSessionsBySubjectID :execrows
UPDATE identity_sessions
SET revoked_at=?,revoked_reason=?
WHERE subject_id=? AND revoked_at IS NULL
`

type RevokeActiveSessionsBySubjectIDParams struct {
	RevokedAt     sql.NullTime   `json:"revoked_at"`
	RevokedReason sql.NullString `json:"revoked_reason"`
	SubjectID     string         `json:"subject_id"`
}

func (q *Queries) RevokeActiveSessionsBySubjectID(ctx context.Context, arg RevokeActiveSessionsBySubjectIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeActiveSessionsBySubjectID, arg.RevokedAt, arg.RevokedReason, arg.SubjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
