// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO identity_sessions(
    id, subject_id, subject_security_version, token_hash, csrf_token_hash,
    session_access, authenticated_at, last_seen_at, expires_at, idle_expires_at,
    revoked_at, revoked_reason, metadata, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID                     string         `json:"id"`
	SubjectID              string         `json:"subject_id"`
	SubjectSecurityVersion int64          `json:"subject_security_version"`
	TokenHash              []byte         `json:"token_hash"`
	CsrfTokenHash          []byte         `json:"csrf_token_hash"`
	SessionAccess          string         `json:"session_access"`
	AuthenticatedAt        time.Time      `json:"authenticated_at"`
	LastSeenAt             time.Time      `json:"last_seen_at"`
	ExpiresAt              time.Time      `json:"expires_at"`
	IdleExpiresAt          time.Time      `json:"idle_expires_at"`
	RevokedAt              sql.NullTime   `json:"revoked_at"`
	RevokedReason          sql.NullString `json:"revoked_reason"`
	Metadata               string         `json:"metadata"`
	CreatedAt              time.Time      `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.SubjectID,
		arg.SubjectSecurityVersion,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.SessionAccess,
		arg.AuthenticatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
