// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_lifecycle.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getActiveSessionSubjectByTokenHash = `-- name: GetActiveSessionSubjectByTokenHash :one
SELECT subject_id
FROM identity_sessions
WHERE token_hash = ?
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveSessionSubjectByTokenHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionSubjectByTokenHash, tokenHash)
	var subject_id string
	err := row.Scan(&subject_id)
	return subject_id, err
}

const revokeActiveSessionByTokenHash = `-- name: RevokeActiveSessionByTokenHash :execrows
UPDATE identity_sessions
SET revoked_at = ?,
    revoked_reason = ?
WHERE token_hash = ?
  AND revoked_at IS NULL
`

type RevokeActiveSessionByTokenHashParams struct {
	RevokedAt     sql.NullTime   `json:"revoked_at"`
	RevokedReason sql.NullString `json:"revoked_reason"`
	TokenHash     []byte         `json:"token_hash"`
}

func (q *Queries) RevokeActiveSessionByTokenHash(ctx context.Context, arg RevokeActiveSessionByTokenHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeActiveSessionByTokenHash, arg.RevokedAt, arg.RevokedReason, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchActiveSession = `-- name: TouchActiveSession :execrows
UPDATE identity_sessions
SET last_seen_at = ?,
    idle_expires_at = ?
WHERE id = ?
  AND revoked_at IS NULL
`

type TouchActiveSessionParams struct {
	LastSeenAt    time.Time `json:"last_seen_at"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
	ID            string    `json:"id"`
}

func (q *Queries) TouchActiveSession(ctx context.Context, arg TouchActiveSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchActiveSession, arg.LastSeenAt, arg.IdleExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
