// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subject_management.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countSubjectsForManagement = `-- name: CountSubjectsForManagement :one
SELECT COUNT(*)
FROM identity_subjects
`

func (q *Queries) CountSubjectsForManagement(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubjectsForManagement)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableSubject = `-- name: DisableSubject :execrows
UPDATE identity_subjects
SET status=?,security_version=security_version+1,disabled_at=?,updated_at=?
WHERE id=? AND status=?
`

type DisableSubjectParams struct {
	Status     string       `json:"status"`
	DisabledAt sql.NullTime `json:"disabled_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ID         string       `json:"id"`
	Status_2   string       `json:"status_2"`
}

func (q *Queries) DisableSubject(ctx context.Context, arg DisableSubjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, disableSubject,
		arg.Status,
		arg.DisabledAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdentifierSubjectID = `-- name: GetIdentifierSubjectID :one
SELECT subject_id
FROM identity_identifiers
WHERE identifier_type=? AND normalized_value=?
`

type GetIdentifierSubjectIDParams struct {
	IdentifierType  string `json:"identifier_type"`
	NormalizedValue string `json:"normalized_value"`
}

func (q *Queries) GetIdentifierSubjectID(ctx context.Context, arg GetIdentifierSubjectIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierSubjectID, arg.IdentifierType, arg.NormalizedValue)
	var subject_id string
	err := row.Scan(&subject_id)
	return subject_id, err
}

const getSubjectForManagement = `-- name: GetSubjectForManagement :one
SELECT s.id,s.status,s.security_version,p.display_name,i.identifier_value,s.created_at,s.updated_at
FROM identity_subjects s
JOIN identity_profiles p ON p.subject_id=s.id
JOIN identity_identifiers i ON i.subject_id=s.id
WHERE s.id=? AND i.identifier_usage=?
`

type GetSubjectForManagementParams struct {
	ID              string `json:"id"`
	IdentifierUsage string `json:"identifier_usage"`
}

type GetSubjectForManagementRow struct {
	ID              string    `json:"id"`
	Status          string    `json:"status"`
	SecurityVersion int64     `json:"security_version"`
	DisplayName     string    `json:"display_name"`
	IdentifierValue string    `json:"identifier_value"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetSubjectForManagement(ctx context.Context, arg GetSubjectForManagementParams) (GetSubjectForManagementRow, error) {
	row := q.db.QueryRowContext(ctx, getSubjectForManagement, arg.ID, arg.IdentifierUsage)
	var i GetSubjectForManagementRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SecurityVersion,
		&i.DisplayName,
		&i.IdentifierValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsForManagement = `-- name: ListSubjectsForManagement :many
SELECT s.id,s.status,s.security_version,p.display_name,i.identifier_value,s.created_at,s.updated_at
FROM identity_subjects s
JOIN identity_profiles p ON p.subject_id=s.id
JOIN identity_identifiers i ON i.subject_id=s.id
WHERE i.identifier_usage=?
ORDER BY s.created_at DESC
LIMIT ? OFFSET ?
`

type ListSubjectsForManagementParams struct {
	IdentifierUsage string `json:"identifier_usage"`
	Limit           int64  `json:"limit"`
	Offset          int64  `json:"offset"`
}

type ListSubjectsForManagementRow struct {
	ID              string    `json:"id"`
	Status          string    `json:"status"`
	SecurityVersion int64     `json:"security_version"`
	DisplayName     string    `json:"display_name"`
	IdentifierValue string    `json:"identifier_value"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListSubjectsForManagement(ctx context.Context, arg ListSubjectsForManagementParams) ([]ListSubjectsForManagementRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsForManagement, arg.IdentifierUsage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsForManagementRow
	for rows.Next() {
		var i ListSubjectsForManagementRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SecurityVersion,
			&i.DisplayName,
			&i.IdentifierValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
