// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countSubjects = `-- name: CountSubjects :one
SELECT COUNT(*)
FROM identity_subjects
`

func (q *Queries) CountSubjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :exec
INSERT INTO identity_subjects(
    id, status, security_version, disabled_at, metadata, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSubjectParams struct {
	ID              string       `json:"id"`
	Status          string       `json:"status"`
	SecurityVersion int64        `json:"security_version"`
	DisabledAt      sql.NullTime `json:"disabled_at"`
	Metadata        string       `json:"metadata"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, createSubject,
		arg.ID,
		arg.Status,
		arg.SecurityVersion,
		arg.DisabledAt,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT
    id,
    status,
    security_version,
    disabled_at,
    metadata,
    created_at,
    updated_at
FROM identity_subjects
WHERE id = ?
`

func (q *Queries) GetSubjectByID(ctx context.Context, id string) (IdentitySubject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByID, id)
	var i IdentitySubject
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SecurityVersion,
		&i.DisabledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
