// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: throttles.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteLoginThrottle = `-- name: DeleteLoginThrottle :exec
DELETE FROM identity_login_throttles
WHERE identifier_hash=? AND source_hash=?
`

type DeleteLoginThrottleParams struct {
	IdentifierHash []byte `json:"identifier_hash"`
	SourceHash     []byte `json:"source_hash"`
}

func (q *Queries) DeleteLoginThrottle(ctx context.Context, arg DeleteLoginThrottleParams) error {
	_, err := q.db.ExecContext(ctx, deleteLoginThrottle, arg.IdentifierHash, arg.SourceHash)
	return err
}

const getLoginThrottle = `-- name: GetLoginThrottle :one
SELECT id,identifier_hash,source_hash,failed_count,window_started_at,locked_until,updated_at
FROM identity_login_throttles
WHERE identifier_hash=? AND source_hash=?
`

type GetLoginThrottleParams struct {
	IdentifierHash []byte `json:"identifier_hash"`
	SourceHash     []byte `json:"source_hash"`
}

func (q *Queries) GetLoginThrottle(ctx context.Context, arg GetLoginThrottleParams) (IdentityLoginThrottle, error) {
	row := q.db.QueryRowContext(ctx, getLoginThrottle, arg.IdentifierHash, arg.SourceHash)
	var i IdentityLoginThrottle
	err := row.Scan(
		&i.ID,
		&i.IdentifierHash,
		&i.SourceHash,
		&i.FailedCount,
		&i.WindowStartedAt,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLoginThrottle = `-- name: UpsertLoginThrottle :exec
INSERT INTO identity_login_throttles(id,identifier_hash,source_hash,failed_count,window_started_at,locked_until,updated_at)
VALUES(?,?,?,?,?,?,?)
ON CONFLICT(identifier_hash,source_hash) DO UPDATE SET
failed_count=excluded.failed_count,window_started_at=excluded.window_started_at,
locked_until=excluded.locked_until,updated_at=excluded.updated_at
`

type UpsertLoginThrottleParams struct {
	ID              string       `json:"id"`
	IdentifierHash  []byte       `json:"identifier_hash"`
	SourceHash      []byte       `json:"source_hash"`
	FailedCount     int64        `json:"failed_count"`
	WindowStartedAt time.Time    `json:"window_started_at"`
	LockedUntil     sql.NullTime `json:"locked_until"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertLoginThrottle(ctx context.Context, arg UpsertLoginThrottleParams) error {
	_, err := q.db.ExecContext(ctx, upsertLoginThrottle,
		arg.ID,
		arg.IdentifierHash,
		arg.SourceHash,
		arg.FailedCount,
		arg.WindowStartedAt,
		arg.LockedUntil,
		arg.UpdatedAt,
	)
	return err
}
